modLoader="javafml"
loaderVersion="[41,)"
license="MIT"
issueTrackerURL="https://github.com/willatendo/Roses-Forge/issues"

[[mods]]
modId="roses"
version="4.0.0"
displayName="Roses"
updateJSONURL="https://github.com/willatendo/Roses-Forge/raw/main/updates.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/roses-forge"
logoFile="roses.png"
authors="Willatendo"
description='''
Brings the past back!
'''

[[dependencies.roses]]
    modId="forge"
    mandatory=true
    versionRange="[41,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.roses]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"