modLoader="javafml"
loaderVersion="[40,)"
license="MIT"
issueTrackerURL="https://github.com/willatendo/Roses-Forge/issues"

[[mods]]
modId="roses"
version="3.3.0"
displayName="Roses"
updateJSONURL="https://github.com/willatendo/Roses-Forge/raw/main/updates.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/roses-forge"
logoFile="roses.png"
authors="Willatendo"
description='''
Brings the past back!
'''

[[dependencies.roses]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.roses]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
    
[[dependencies.roses]]
    modId="tyrannotitanlib"
    mandatory=true
    versionRange="[v4.2.0,)"
    ordering="NONE"
    side="BOTH"