modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
issueTrackerURL="https://github.com/willatendo/Roses-Forge/issues"

[[mods]]
modId="roses"
version="5.0.0"
displayName="Roses"
updateJSONURL="https://github.com/willatendo/Roses-Forge/raw/main/updates.json"
displayURL="https://github.com/willatendo/Roses"
# logoFile="roses_logo.png"
authors="Willatendo"
description='''
Brings the past back!
'''

[[dependencies.roses]] 
    modId="forge" 
    mandatory=true 
    versionRange="[47,)" 
    ordering="NONE"
    side="BOTH"
    
[[dependencies.roses]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"