modLoader="javafml"
loaderVersion="[36,)"
license="MIT"
issueTrackerURL="https://github.com/willatendo/Roses-Forge/issues"

[[mods]]
modId="roses"
version="2.0.1"
displayName="Roses"
updateJSONURL="https://github.com/willatendo/Roses-Forge/raw/main/updates.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/roses-forge"
logoFile="roses.png"
authors="Willatendo"
description='''
Brings the past back!
'''

[[dependencies.roses]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.roses]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
    
[[dependencies.roses]]
    modId="tyrannotitanlib"
    mandatory=true
    versionRange="[v1.2.3,)"
    ordering="NONE"
    side="BOTH"